### ISSUE TITLE
Site extension NOT working

### ISSUE THREAD

**Issue by bpasham** [gregjhogan/redirect-http-to-https-site-extension#9]
I installed and restarted - tried several times.. it's not redirecting at all. Since there is nothing more I can configure in the extension, I am posting it as an issue, so tat if you can point to a fix.

Great effort to make such a useful feature simple though.

**Comment by bpasham** [comment]
filters.Add(new RequireHttpsAttribute()); not working on the site either. https is working fine if I explicitly go there

**Comment by farlop** [comment]
+1

**Comment by HerrNiklasRaab** [comment]
+1

**Comment by gregjhogan** [comment]
Sounds similar to #1 and #2 ... did you fully restart the web app?
 
https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#private-extensions

> Also, note that the Restart button on the Site Extension Kudu tab only restarts the scm site (by just killing the process). If your xdt effects the Main site, you will need to either kill the non-Scm w3wp.exe in Kudu's Process Explorer, or fully restart the site from the Azure Portal.

**Comment by ziriax** [comment]
This strange, 3 weeks ago this extension seemed to work fine, now it stopped working for me, even after fully restarting the app service...

**Comment by xt0rted** [comment]
I just ran into this as well. I first tried putting these rules into my own `applicationHost.xdt` which didn't work, and then installed this extension which also didn't work. The end result was I had to move my url rewrite rules back into my `web.config`.

I asked about this in https://github.com/projectkudu/kudu/issues/2598 but for now I'm moving back to the web.config setup since that does work.

A side note, in my case the rules to remove custom & server headers continue to work in the `applicationHost.xdt`, it's just the url rewriting that's not.

**Comment by gregjhogan** [comment]
I believe I may have found the issue.  See da5e8b2 for more details.  No idea why this suddenly broke!

I pushed out a new version of the site extension.  Can you try upgrading it on your site and see if it starts working now?

**Comment by ashwanidv100** [comment]
I tried Version 1.0.0 but It Still not working for me as well.

**Comment by xt0rted** [comment]
I didn't try the new version, but the custom [applicationHost.xdt](https://gist.github.com/xt0rted/33b554069e94e00cb76f1dc327fd7e0f) I was trying to use was setup the same way and didn't work either. I originally based my file on the sample from the [Kudu wiki](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples#redirect-http-traffic-to-https).

My testing so far has shown that the rewrite rules are not applied to my site at all. I have multiple copies running in multiple subscriptions and none of them apply the settings from `applicationHost.xdt`.

I've setup a test site, applied the applicationHost.xdt I linked above, and that works. I've yet to be able to track down what's causing this issue though. I'm hoping to have some time over the weekend to look into this more.
